Nearblocks/nearblocks

api/src/config.ts, api/src/libs/schema/key.ts, api/src/routes/index.ts, api/src/routes/key.ts, api/src/services/key.ts
Added api for retrieving access key information, including account id, by using the public key
closes #16
=> feat(api): add access key info api

apps/indexer-balance/src/config.ts, apps/indexer-balance/src/services/balance.ts, apps/indexer-balance/src/services/stream.ts, apps/indexer-base/src/config.ts, apps/indexer-base/src/services/accessKey.ts, apps/indexer-events/src/config.ts
indexing failed at block 22633808 due to an error [https://github.com/near/near-microindexers/issues/1](https://github.com/near/near-microindexers/issues/1) to skip the issue we started from the next block
=> fix(indexer-balance): restart indexing from 22633809, fix logs

apps/app/src/pages/blocks/index.tsx, apps/app/src/pages/index.tsx, apps/app/src/pages/txns/index.tsx, apps/bos-components/src/components/Blocks/Latest.tsx, apps/bos-components/src/components/Blocks/List.tsx, apps/bos-components/src/components/Transactions/Latest.tsx, apps/bos-components/src/components/Transactions/List.tsx, apps/bos-components/src/components/Transactions/Overview.tsx, apps/bos-components/src/includes/formats.ts, apps/bos-components/src/includes/icons/CloseCircle.tsx, apps/bos-components/src/includes/near.ts, apps/bos-components/src/includes/types.ts, apps/bos-components/src/public/styles.css
=> feat(bos-component): add url props for pagination and filtering

apps/app/next.config.js
=> feat(app): redirect on /transactions/xxx to /txns/xxx

apps/api/src/routes/index.ts, apps/api/src/routes/legacy.ts, apps/api/src/services/legacy.ts, apps/explorer-selector/next.config.js
=> feat: add circulating supply apis

apps/backend/src/index.ts, apps/backend/src/libs/lcw.ts, apps/backend/src/services/dailyStats.ts, apps/backend/src/services/stats.ts
disable total supply job for now, add logs
=> feat(backend): add circulating supply in stats job

apps/backend/migrations/20240206090209_errored_contracts_index.js, apps/backend/migrations/20240206090209_errored_contracts_index.up.sql
fixes nft token on conflict errors
=> fix: update errored contract unique indexes

apps/api/src/services/account/index.ts, apps/backend/src/services/dailyStats.ts, apps/explorer-selector/README.md
fix explorer-selector docker build command
=> fix(api): fix account inventory api errors

apps/bos-components/src/components/Transactions/Execution.tsx, apps/bos-components/src/components/Transactions/Hash.tsx, apps/bos-components/src/components/Transactions/ReceiptInfo.tsx, apps/bos-components/src/components/Transactions/ReceiptKind.tsx, apps/bos-components/src/components/Transactions/TransactionReceipt.tsx, apps/bos-components/src/includes/Common/Receipts/Action/FunctionCall.tsx, apps/bos-components/src/includes/Common/Receipts/ReceiptStatus.tsx, apps/bos-components/src/includes/near.ts, apps/bos-components/src/includes/types.ts
=> feat(bos-components): add transaction execution enhancements

apps/api/src/libs/schema/kitwallet.ts, apps/api/src/routes/kitwallet.ts, apps/api/src/services/kitwallet.ts
- account staking deposits api
- account activities api
- account call receivers api
=> feat(api): add kitwallet apis

apps/api/src/libs/schema/account.ts, apps/api/src/libs/schema/blocks.ts, apps/api/src/libs/schema/fts.ts, apps/api/src/libs/schema/nfts.ts, apps/api/src/libs/schema/txns.ts, apps/api/src/libs/schema/validators.ts, apps/api/src/routes/account.ts, apps/api/src/routes/blocks.ts, apps/api/src/routes/fts.ts, apps/api/src/routes/nfts.ts, apps/api/src/routes/txns.ts, apps/api/src/services/account/ft.ts, apps/api/src/services/account/nft.ts, apps/api/src/services/fts/index.ts, apps/api/src/services/nfts/contract.ts, apps/api/src/services/nfts/index.ts, apps/api/src/services/nfts/tokens.ts, apps/bos-components/src/components/Address/NFTTransactions.tsx, apps/bos-components/src/components/Address/TokenTransactions.tsx, apps/bos-components/src/components/FT/List.tsx, apps/bos-components/src/components/FT/Transfers.tsx, apps/bos-components/src/components/FT/TransfersList.tsx, apps/bos-components/src/components/NFT/List.tsx, apps/bos-components/src/components/NFT/TokenTransfers.tsx, apps/bos-components/src/components/NFT/Transfers.tsx, apps/bos-components/src/components/NFT/TransfersList.tsx
=> fix(api+bos): remove api page limit, fix ft/nft apis & token listings

apps/app/src/components/Layouts/Footer.tsx
=> fix(app): remove near KYC platform link

apps/api/src/libs/schema/analytics.ts, apps/api/src/libs/utils.ts, apps/api/src/routes/analytics.ts, apps/api/src/routes/index.ts, apps/api/src/services/account/ft.ts, apps/api/src/services/account/index.ts, apps/api/src/services/account/key.ts, apps/api/src/services/account/nft.ts, apps/api/src/services/analytics/account.ts, apps/api/src/services/txns.ts
=> feat(api): add account historical balance api

apps/api/src/services/fts/index.ts, apps/backend/src/index.ts, apps/backend/src/jobs/circulating-supply.ts, apps/backend/src/libs/lcw.ts, apps/backend/src/libs/ref.ts, apps/backend/src/services/dailyStats.ts, apps/backend/src/services/fts.ts, apps/backend/src/services/stats.ts, apps/backend/src/services/supply.ts
- seperate circulating supply job from stats
- calculate near btc price
- fix token count api
=> feat(backend): use ref finance token price api

apps/app/package.json, apps/app/src/components/Layouts/Header.tsx, yarn.lock
Please, go through these steps before you submit a PR.
1. Make sure that your PR is not a duplicate.
2. If not, then make sure that:
a. You have done your changes in a separate branch. Branches MUST have descriptive names that start with either the `fix/` or `feat/` prefixes. Good examples are: `fix/signin-issue` or `feat/issue-templates`.
b. You have a descriptive commit message with a short title (first line).
c. You have only one commit (if not, squash them into one commit).
d. Make sure `yarn lint` & `yarn format` doesn't throw any error. If it does, fix them first and amend your commit (`git commit --amend`).
3. **After** these steps, you're ready to open a pull request.
a. Give a descriptive title to your PR.
b. Provide a description of your changes.
c. Put `closes #XXXX` in your …
=> add Ukrainian locale

apps/api/src/services/sync.ts, apps/backend/src/index.ts, apps/backend/src/services/tasks.ts
- add new stats job to sync status api
- update backend job intervals
=> fix(backend+api): fix nodes api data missing issue

apps/api/src/libs/schema/account.ts, apps/api/src/routes/account.ts, apps/api/src/services/account/stake.ts, apps/api/src/services/nfts/tokens.ts, apps/api/src/types/types.ts
=> feat(api): add account stake txns api

apps/api/src/libs/schema/account.ts, apps/api/src/routes/account.ts, apps/api/src/services/account/activity.ts, apps/api/src/services/account/txn.ts, apps/api/src/services/charts.ts
- add deposit in account txn actions
- decrease tps chart timeframe
=> feat(api): add account balance changes api

apps/api/src/libs/stream.ts, apps/backend/migrations/20240618132551_backend_stats_indexes.js, apps/backend/migrations/20240618132551_backend_stats_indexes.up.sql, apps/backend/src/index.ts, apps/backend/src/services/dailyStatsNew.ts, apps/backend/src/services/fts.ts, apps/backend/src/services/nfts.ts
=> fix(backend): optimize stats & meta queries, fix api crash

apps/app/src/components/vm/VmInitializer.tsx, apps/bos-components/src/includes/Utils/libs.tsx
Reverts Nearblocks/nearblocks#373
=> Revert "fix(bos-components): update rpc urls"

apps/bos-components/src/components/Contract/ViewOrChange.tsx, apps/bos-components/src/components/Contract/ViewOrChangeAbi.tsx, apps/bos-components/src/components/FT/TokenFilter.tsx
=> fix(bos-components): attached deposit and gas fields are not passing issue in contract page

apps/api/src/services/account/index.ts, apps/api/src/services/sync.ts
=> fix(api): increase token holders sync block limit

apps/api/src/services/txns.ts
=> feat(api): include json args in txns apis

apps/app/src/components/Address/NFTTransactions.tsx, apps/app/src/components/Address/TokenTransactions.tsx, apps/app/src/components/Address/Transactions.tsx, apps/app/src/components/Layouts/Footer.tsx, apps/app/src/components/Layouts/Header.tsx, apps/app/src/components/Tokens/FT/Holders.tsx, apps/app/src/components/Tokens/FT/Transfers.tsx, apps/app/src/components/Tokens/NFT/Holders.tsx, apps/app/src/components/Tokens/NFT/TokenTransfers.tsx, apps/app/src/components/Tokens/NFT/Transfers.tsx, apps/app/src/components/Transactions/List.tsx, apps/app/src/components/common/Filters.tsx, apps/app/src/pages/address/[id].tsx
=> fix(app): token txns and nft token txns tabs not updated on account change

apps/app/package.json, apps/app/src/components/Blocks/Detail.tsx, apps/app/src/components/Icons/ListCheck.tsx, apps/app/src/components/Icons/Rpc.tsx, apps/app/src/components/Layouts/Header.tsx, apps/app/src/components/Layouts/Menu.tsx, apps/app/src/components/Layouts/RpcMenu.tsx, apps/app/src/components/NodeExplorer/Delegators.tsx, apps/app/src/components/Transactions/Details.tsx, apps/app/src/components/Transactions/TreeReceipts/TreeReceipt.tsx, apps/app/src/hooks/useRpc.ts, apps/app/src/pages/address/[id].tsx, apps/app/src/pages/node-explorer/[id].tsx, apps/app/src/pages/node-explorer/index.tsx, apps/app/src/pages/txns/[hash].tsx, apps/app/src/stores/rpc.ts, apps/app/src/utils/libs.ts, apps/app/src/utils/near.ts, apps/app/src/utils/rpc.ts, yarn.lock
=> feat(app): display rpc data and rpc switching on api error

apps/app/next.config.js
=> feat(app): add redirect for NEP-518 /block links

apps/api/src/services/kitwallet.ts, apps/backend/migrations/20241108151848_staking_pools.js, apps/backend/migrations/20241108151848_staking_pools.up.sql, apps/backend/src/jobs/refresh-views.ts
Use materalized views to improve kitwallet stake pools response time
=> feat(backend): create materialized views for staking pools

apps/app/src/components/Transactions/Details.tsx, apps/app/src/components/Transactions/Receipts/Action/FunctionCall.tsx, apps/app/src/components/Transactions/Receipts/ReceiptRow.tsx, apps/app/src/components/Transactions/Receipts/RlpTransaction.tsx, apps/app/src/components/common/NEPTokenTransactions.tsx, apps/app/src/components/common/TokenInfo.tsx, apps/app/src/pages/_document.tsx, apps/app/src/styles/globals.css, apps/app/src/utils/libs.ts, apps/app/src/utils/near.ts, apps/app/src/utils/types.ts
Temporarily show NEP-245 events from receipt json until we index these events
=> feat(app): show NEP-245 token transactions

apps/api/src/services/account/index.ts
Adds back balance information removed by #694  with data from balance indexer
**Example of previous response:**
```
{
"account": [
{
"account_id": "example_account.near",
"created": {
"transaction_hash": "HzVK1mAcH7zXnU37RCJZBLoZ4NWvN1sNaNFZX7TYaeKt",
"block_timestamp": 1632485751346823400
},
"deleted": {
"transaction_hash": null,
"block_timestamp": null
}
}
]
}
```
**Example of new response:**
```
{
"account": [
{
"account_id": "example_account.near",
"created": {
"transaction_hash": "HzVK1mAcH7zXnU37RCJZBLoZ4NWvN1sNaNFZX7TYaeKt",
"block_timestamp": 1632485751346823400
},
"deleted": {
"transaction_hash": null,
"block_timestamp": null
},
"amount": "2015088987500000000000",
"locked": "0",
"block_height": 48543062,
"block_hash": "9hvt7fYfVDKjKdD5wKFkmXWtm8XHjfFyzXsn5beSM544"
}
]
}
```
=> fix(api): add balance and block info in account api

apps/api/src/services/account/index.ts
This PR updates \account\ endpoint to return the latest block hash and block height, mimicking response from RPC
**Previous Behavior**: The endpoint returned the block hash and block height of the block where the account's balance was last updated ( #701 )
=> fix(api): add latest block details to account api

apps/backend/src/services/tasks.ts
Fixes the issue reported in #703
=> fix(backend): fetch and store staking pool metadata iteratively

apps/api/src/services/validators.ts
Add caching based on epoch id and latest block id to reduce rpc calls
=> fix(api): add caching for last epoch apy calculation in validator api

apps/backend/migrations/20241223162529_block_bytea.js, apps/backend/migrations/20241223162529_block_bytea.up.sql, apps/indexer-base/src/services/block.ts, apps/indexer-base/src/services/executionOutcome.ts, apps/indexer-base/src/services/receipt.ts, apps/indexer-base/src/services/transaction.ts, packages/nb-blocks/package.json, packages/nb-blocks/src/index.ts, packages/nb-neardata/package.json, packages/nb-neardata/src/index.ts, packages/nb-types/package.json, packages/nb-types/src/tables.ts
- update nb-data package to use bytea  data
- move batch insertion loop outside the retry block
=> feat(indexer): store block data in bytea column to speed up inserts

apps/api/src/services/txns.ts
/txns/:hash/full endpoint now returns recipt logs as json
=> fix(api): add receipt logs in txn details response

apps/app/src/components/Transactions/Receipts/Action/FunctionCall.tsx, apps/app/src/components/Transactions/Receipts/ReceiptInfo.tsx, apps/app/src/components/Transactions/Receipts/ReceiptKind.tsx, apps/app/src/components/Transactions/Receipts/ReceiptRow.tsx
=> fix(app): update transaction action log to display float numbers as string

packages/nb-neardata/package.json, packages/nb-neardata/src/index.ts
=> fix(packages): fix final block fetching issues in fastnear data streamer

apps/app/src/components/Layouts/Header.tsx, apps/app/src/components/Transactions/Execution.tsx, apps/app/src/components/Transactions/Receipt.tsx, apps/app/src/components/Transactions/ReceiptSummary.tsx, apps/app/src/components/Transactions/Tree.tsx
temporarily commented out the txn pending check
=> fix(app): keep out-of-sync banner always visible

apps/app/src/components/app/Layouts/Header.tsx, apps/app/src/components/app/Layouts/Layout.tsx, apps/app/src/components/app/Layouts/LayoutActions.tsx, apps/app/src/components/app/common/Search.tsx, apps/app/src/stores/app/syncStats.ts, apps/app/src/utils/app/actions.ts, apps/app/src/utils/app/rpc.ts
=> fix(app): resolve rpc search issue in beta

apps/app/public/opensearch_mainnet.xml, apps/app/public/opensearch_testnet.xml, apps/app/src/components/app/Layouts/Layout.tsx, apps/app/src/components/app/Layouts/LayoutActions.tsx, apps/app/src/utils/app/config.ts
=> fix(app): update chrome search on beta

apps/app/src/components/app/Transactions/Action/Intents/Burn.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/utils/near.ts
- bug fix on transaction actions
=> fix(app): correct withdraw issue on transaction details page on beta

apps/api/src/services/account/index.ts, apps/backend/migrations/20250219112242_balance_events_sort_idx.js, apps/backend/migrations/20250219112242_balance_events_sort_idx.up.sql
=> fix(api): fix account balance api sorting

.github/workflows/workflow-build.yaml, apps/indexer-s3/src/services/stream.ts, packages/nb-neardata/src/index.ts
=> fix(indexer): increase batch size for s3 indexer

apps/app/src/pages/_app.tsx, apps/app/src/pages/blocks/[hash].tsx, apps/app/src/utils/config.ts
- update default value of GTM_ID
=> fix(app): txns shows zero when out-of-sync on block details

apps/indexer-base/package.json, apps/indexer-base/src/config.ts, apps/indexer-base/src/libs/utils.ts, apps/indexer-base/src/services/s3.ts, apps/indexer-base/src/types/types.ts, packages/nb-neardata/package.json, packages/nb-neardata/src/index.ts, yarn.lock
=> fix(indexer): resolve sync issues with fastnear

apps/app/public/scripts/ad-unit-manager.react.js, apps/app/src/components/app/Ad.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/skeleton/txns/TxnsTabs.tsx, apps/app/src/utils/app/config.ts
- add default GTM tag on explorer selector
- fix type error from growthmate ads
- fix position of new over enhanced plan tab on skeleton
=> fix(app): ads jumping issue in transaction details on beta

apps/app/package.json, apps/app/src/components/app/Blocks/Details.tsx, apps/app/src/components/app/Charts/Chart.tsx, apps/app/src/components/app/Transactions/Action/Intents/Burn.tsx, apps/app/src/components/app/Transactions/Action/Intents/index.tsx, apps/app/src/components/app/Transactions/Action/index.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/Transactions/Overview.tsx, apps/app/src/components/app/common/TokenInfo.tsx, yarn.lock
- rpc error handling on txns details
- updated translation repo
=> fix(app): correct withdraw issue on transaction details

apps/app/src/components/app/Blocks/Details.tsx, apps/app/src/components/app/Home/Home.tsx, apps/app/src/components/app/Layouts/LayoutActions.tsx, apps/app/src/components/app/Transactions/Receipts/Action/AddKey.tsx, apps/app/src/components/app/common/Search.tsx, apps/app/src/hooks/app/useSearchHistory.ts, apps/app/src/utils/app/actions.ts, apps/app/src/utils/app/rpc.ts, apps/app/src/utils/types.ts
- transactions stuck on loading on testnet block details
- add copy button to public key on execution plan
=> feat(app): caching search history on beta

apps/app/src/components/app/Tokens/FT/Holders.tsx, apps/app/src/components/app/wallet/web3modal.ts, apps/app/src/utils/app/config.ts
=> fix(app): token page percentage and quantity cal issue on beta

apps/api/src/services/account/activity.ts, apps/backend/migrations/20250312144444_update_nft_list.js, apps/backend/migrations/20250312144444_update_nft_list.up.sql
- add block timestamp in account activities api
=> fix(backend): update nft list view to use new nft holders tables

apps/app/src/components/app/Address/AccountAlertsActions.tsx, apps/app/src/components/app/Address/AccountMoreInfoActions.tsx, apps/app/src/components/app/Address/AccountOverviewActions.tsx, apps/app/src/components/app/common/Button.tsx, apps/app/src/components/app/common/Table.tsx
- address page access key alert not showing
=> fix(app): style issue on common table and address page

apps/app/src/components/app/Address/AccessKeyRow.tsx, apps/app/src/components/app/Address/AddressValidator.tsx, apps/app/src/components/app/Address/NFTTxnsActions.tsx, apps/app/src/components/app/Address/ReceiptActions.tsx, apps/app/src/components/app/Address/TokenTxnsActions.tsx, apps/app/src/components/app/Address/TransactionActions.tsx, apps/app/src/components/app/Blocks/Details.tsx, apps/app/src/components/app/Blocks/ListActions.tsx, apps/app/src/components/app/ChainAbstraction/MultiChainTxns.tsx, apps/app/src/components/app/Charts/Chart.tsx, apps/app/src/components/app/Charts/TpsChart.tsx, apps/app/src/components/app/Layouts/Footer.tsx, apps/app/src/components/app/Layouts/Header.tsx, apps/app/src/components/app/NodeExplorer/NodeListActions.tsx, apps/app/src/components/app/Tokens/FT/Transfers.tsx, apps/app/src/components/app/Tokens/FTTransfersActions.tsx, apps/app/src/components/app/Tokens/NFT/NFTInventory.tsx, apps/app/src/components/app/Tokens/NFT/NFTTransfers.tsx, apps/app/src/components/app/Tokens/NFT/TokenTransfers.tsx, apps/app/src/components/app/Tokens/NFTTransfersActions.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/Transactions/ListActions.tsx, apps/app/src/components/app/common/TableSummary.tsx, apps/app/src/components/app/common/TimeStamp.tsx, apps/app/src/components/app/skeleton/blocks/hash.tsx, apps/app/src/components/app/skeleton/charts/Detail.tsx, apps/app/src/components/app/skeleton/home/Home.tsx, apps/app/src/components/app/skeleton/txns/Overview.tsx
- fix transaction details jumping issue in testnet
- change age/datetime showing to common component
- fix node validator account name and public key joined together in single line on testnet
- fix inventory showing empty space in nft token details page if contain zero inventory
- hide multi chain transaction
- display issue of 'address does not exist' on account page
=> fix(app): white line showing on scroll in tables

apps/app/src/components/app/Address/Contract/VerifiedData.tsx
=> feat(app): add download button on contract tab to download contract wasm

apps/app/src/app/[locale]/address/[id]/layout.tsx, apps/app/src/app/[locale]/address/[id]/page.tsx, apps/app/src/app/[locale]/txns/[hash]/layout.tsx, apps/app/src/components/app/Address/AccessKeyRow.tsx, apps/app/src/components/app/Address/AddressValidator.tsx, apps/app/src/components/app/Address/Contract/OverviewActions.tsx, apps/app/src/components/app/Address/Contract/VerifiedData.tsx, apps/app/src/components/app/Address/ReceiptActions.tsx, apps/app/src/components/app/Address/TransactionActions.tsx, apps/app/src/components/app/Layouts/Footer.tsx, apps/app/src/components/app/Transactions/ListActions.tsx, apps/app/src/components/app/common/TokenHoldings.tsx, apps/app/src/hooks/app/useRpc.ts, apps/app/src/utils/app/actions.ts
=> fix(app): convert ethereum addresses to lowercase on account page

apps/app/src/components/app/Transactions/TxnsTabActions.tsx, apps/app/src/components/app/Transactions/TxnsTabs.tsx, apps/app/src/components/app/common/CursorPaginator.tsx, apps/app/src/components/app/common/Paginator.tsx
- dark mode text issue on hover in pagination
=> fix(app): status updating issue of pending transactions

apps/indexer-receipts/src/services/receipt.ts
Index Action & Data receipts only
=> fix(indexer): filter receipts

apps/app/src/app/[locale]/node-explorer/page.tsx, apps/app/src/components/app/Layouts/Header.tsx, apps/app/src/components/app/Layouts/Layout.tsx, apps/app/src/components/app/Layouts/LayoutActions.tsx, apps/app/src/components/app/NodeExplorer/NodeListActions.tsx, apps/app/src/components/app/common/Notice.tsx, apps/app/src/components/app/skeleton/node-explorer/Index.tsx, apps/app/src/hooks/app/useRpc.ts, apps/app/src/utils/types.ts
- add rpc switcher to validator explorer
- add 'This blockchain explorer is out of sync. Some charts may be delayed.' notice
=> feat(app): protocol version and next seat price to validator explorer

apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/common/RpcStatus.tsx, apps/app/src/components/app/common/Status.tsx, apps/app/src/components/app/common/TokenInfo.tsx
- loader added for error message, updated to single line in case of transaction failure
- undefined bug in transaction action
=> fix(app): error message display issue on transaction status

apps/app/src/components/app/Address/Contract/VerifiedData.tsx, apps/app/src/components/app/Address/Contract/ViewOrChange.tsx, apps/app/src/components/app/Address/Contract/ViewOrChangeAbi.tsx, apps/app/src/components/app/Tokens/FT/OverviewActions.tsx, apps/app/src/components/app/common/TokenHoldings.tsx
- download contract wasm style issue
- dark mode and style fixes on contract methods
=> fix(app): use decimal (non scientific) token prices on address page

apps/indexer-receipts/src/libs/utils.ts, apps/indexer-receipts/src/services/cache.ts, apps/indexer-receipts/src/services/executionOutcome.ts, apps/indexer-receipts/src/services/receipt.ts, apps/indexer-receipts/src/services/stream.ts, packages/nb-blocks/package.json, packages/nb-blocks/src/index.ts, yarn.lock
- add request handler with timeouts in s3 fetcher
=> fix(indexer): remove bulk processing of receipts

apps/app/src/app/ErrorLayout.tsx, apps/app/src/app/[locale]/hash/[receipt]/page.tsx, apps/app/src/components/app/Layouts/Header.tsx, apps/app/src/components/app/Layouts/LayoutActions.tsx, apps/app/src/components/app/common/Search.tsx, apps/app/src/utils/app/actions.ts, apps/app/src/utils/app/rpc.ts
- Search blinking issue on page reload
- Search icon loader not displaying
- Page reload on search
- Toast notification not showing on global error page
=> fix(app): handle rpc rate limiting on search

apps/indexer-balance/README.md, apps/indexer-balance/package.json, apps/indexer-balance/src/config.ts, apps/indexer-balance/src/libs/utils.ts, apps/indexer-balance/src/services/balance.ts, apps/indexer-balance/src/services/stream.ts, apps/indexer-balance/src/types/types.ts, packages/nb-blocks-minio/.eslintignore, packages/nb-blocks-minio/.eslintrc.cjs, packages/nb-blocks-minio/package.json, packages/nb-blocks-minio/src/index.ts, packages/nb-blocks-minio/src/knex.d.ts, packages/nb-blocks-minio/src/type.ts, packages/nb-blocks-minio/tsconfig.json, yarn.lock
- use minio js client for s3 data fetching
=> feat(indexer): add support for multiple instances in balance indexer

apps/indexer-balance/src/config.ts, apps/indexer-events/README.md, apps/indexer-events/package.json, apps/indexer-events/src/config.ts, apps/indexer-events/src/libs/guards.ts, apps/indexer-events/src/libs/utils.ts, apps/indexer-events/src/services/contracts/ft/index.ts, apps/indexer-events/src/services/events.ts, apps/indexer-events/src/services/ft.ts, apps/indexer-events/src/services/nft.ts, apps/indexer-events/src/services/stream.ts, apps/indexer-events/src/types/types.ts, apps/indexer-signature/README.md, apps/indexer-signature/package.json, apps/indexer-signature/src/config.ts, apps/indexer-signature/src/libs/guards.ts, apps/indexer-signature/src/libs/utils.ts, apps/indexer-signature/src/services/signature.ts, apps/indexer-signature/src/services/stream.ts, apps/indexer-signature/src/types/types.ts, apps/indexer-staking/README.md, apps/indexer-staking/package.json, apps/indexer-staking/src/config.ts, apps/indexer-staking/src/libs/utils.ts, apps/indexer-staking/src/services/staking.ts, apps/indexer-staking/src/services/stream.ts, apps/indexer-staking/src/types/types.ts
- events indexer
- staking indexer
- signature indexer
=> feat(indexer): support for multiple instances in indexer

apps/app/src/components/app/Address/AccessKeyRow.tsx, apps/app/src/components/app/Address/NFTTxnsActions.tsx, apps/app/src/components/app/Address/ReceiptActions.tsx, apps/app/src/components/app/Address/TokenTxnsActions.tsx, apps/app/src/components/app/Address/TransactionActions.tsx, apps/app/src/components/app/Blocks/Details.tsx, apps/app/src/components/app/Blocks/ListActions.tsx, apps/app/src/components/app/ChainAbstraction/MultiChainTxns.tsx, apps/app/src/components/app/Tokens/FT/Transfers.tsx, apps/app/src/components/app/Tokens/FTTransfersActions.tsx, apps/app/src/components/app/Tokens/NFT/NFTTransfers.tsx, apps/app/src/components/app/Tokens/NFT/TokenTransfers.tsx, apps/app/src/components/app/Tokens/NFTTransfersActions.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/Transactions/ListActions.tsx, apps/app/src/components/app/common/TimeStamp.tsx, apps/app/src/components/app/common/Timestamp.tsx, apps/app/src/utils/app/dayjs.ts
- **Component Rename**: Changed `TimeStamp` → `Timestamp` (camelCase)  
- Updated all component imports/references  
- Maintained identical functionality
=> fix(app): dayjs relative time format by explicitly setting locale to en

apps/indexer-signature/Dockerfile, apps/indexer-signature/migrations/20250430122515_init.up.sql, apps/indexer-signature/src/libs/guards.ts, apps/indexer-signature/src/libs/utils.ts, apps/indexer-signature/src/services/signature.ts, apps/indexer-signature/src/services/stream.ts, apps/indexer-signature/src/types/types.ts, packages/nb-types/src/tables.ts
- accommodate recent signature changes
=> fix(indexer): remove serial key from signature indexer

apps/app/src/components/app/Address/Contract/ViewOrChange.tsx, apps/app/src/components/app/Address/Contract/ViewOrChangeAbi.tsx, apps/app/src/components/app/Icons/FaChevronDown.tsx, apps/app/src/components/app/Tokens/MT/OverviewActions.tsx, apps/app/src/components/app/Transactions/Details.tsx, apps/app/src/components/app/Transactions/Receipts/TransactionActions.tsx, apps/app/src/components/app/common/Status.tsx
- style issue on query select field
- `mt-token` page contract field linking
- status not showing on pending state on txns details
- delegate actions public key showing wrong on execution tab
=> fix(app): add method query validation with formik and yup

apps/api/src/libs/fetchTokenMeta.ts, apps/api/src/services/v2/account/index.ts, apps/app/src/components/app/common/TokenHoldings.tsx, apps/app/src/utils/types.ts
All token types are now returned under mts since they originate from intents.near. Removed fts and nfts
=> fix(api): update inventory response to return all token types under mts

apps/app/src/components/app/Address/Contract/Info.tsx, apps/app/src/components/app/Transactions/Receipts/Action/DeployGlobalContract.tsx, apps/app/src/components/app/Transactions/Receipts/Action/DeployGlobalContractByAccountId.tsx, apps/app/src/components/app/Transactions/Receipts/Action/UseGlobalContract.tsx, apps/app/src/components/app/Transactions/Receipts/Action/UseGlobalContractByAccountId.tsx, apps/app/src/components/app/Transactions/Receipts/ReceiptKind.tsx, apps/app/src/components/app/Transactions/TxnsTabActions.tsx, apps/app/src/utils/app/near.ts, apps/app/src/utils/types.ts
- add new field (Global Contract Account & Global Contract Hash) on contract info tab
=> feat(app): add global contract args support

apps/app/src/components/app/common/Search.tsx
- search request spamming on subsequent enter presses
=> feat(app): show spinner during debounce search
